### ISSUE TITLE
GUI for non-pokemobs

### ISSUE THREAD

**Issue by TupperBot99** [Pokecube-Development/Pokecube-Issues-and-Wiki#1055]
**Is your feature request related to a problem? Please describe.**
I believe the option for vanilla_pokemobs and non_vanilla_pokemobs is a really cool feature, though it is limited in the fact that you can't open the GUI to change AI options and what not.

**Describe the solution you'd like**
Make it possible to open the GUI with non-pokemobs when caught, letting you at the least change their AI options and maybe access their inventory if possible, like perhaps if a zombie you caught was wearing armor you can take it from him, or maybe give him a new set of armor and a weapon!

**Describe alternatives you've considered**
Right now you can only use the change stance button to switch between sitting or following with a caught non-pokemob, which works for what I am wanting though it would be nice if they could roam around when not accompanying me

**Additional context**
I found out about this feature when looking through the /pokesettings command, and it seemed to be a solution for my "befriend all mobs" thing I've been looking for. Just feels like there is more potential with this feature.

**Comment by Thutmose** [comment]
So it turns out, you can access their screen by right clicking them with a pokedex. This was done as to not interfere with normal right click behaviour otherwise.

I will however look into improvements for their gui, such as ability to set held items.
Armour can already be set via the wearables gui, which you can access from their main gui
The next update also adds an offhand slot for them in the main gui (though was also available via wearables gui)

**Comment by Thutmose** [comment]
the change mentioned here should now be in 3.18.1, github release is out, curseforge one is pending approval
