### ISSUE TITLE
Marshadow Shiny

### ISSUE THREAD

**Issue by HeroBlindNation** [Pokecube-Development/Pokecube-Issues-and-Wiki#314]
**Describe the solution you'd like**
For Marshadow to have a shiny (its shiny colors are only shown when its fighting)

**Additional context**
Green is normal and purple is shiny. (both shiny and non shiny are black but their colors change when its fighting)
![200px-Shiny_Marshadow_Comparison](https://user-images.githubusercontent.com/43615714/80402307-58323480-8883-11ea-95ba-632633e7c740.png)

**Comment by MetaltyrantMk2** [comment]
Theres a few different issues with some other models too:
Wishiwashi schools use the texture of a normal wishiwashi
Sentret and Furret heads have errors with them
Finneon fins can appear invisible if looked from a certain angle
Some flying insect wings can also disappear with a similar effect to the finneon fins i think beautifly was one (its possible that this has been fixed and i haven't seen them since)

**Comment by Thutmose** [comment]
re-append these comments onto #319 please
