### ISSUE TITLE
[Possible bug] Pokemobs on shoulder should stay on it when jumping

### ISSUE THREAD

**Issue by CorentG** [Pokecube-Development/Pokecube-Issues-and-Wiki#40]
**Is your feature request related to a problem? Please describe.**
At one point, when a pokemon was on a player shoulder, he stayed on it, even when jumping. Parrots in vanilla minecraft dismount when the player lose altitude (1 block), wich is very annoying. Now pokemons are doing it too, and it's not fun.

**Describe the solution you'd like**
Bringing back this feature, that disapeared some version ago for an unknow reason (I remember filling an issue about 1 pokemon appear in both shoulder, thus taking both slots, maybe it come from here)

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Thutmose** [comment]
So the reason it disappeared, was vanilla broke it between 1.7.10 and 1.12 or whenever they added parrots. Before 1.7.10, it was possible to save a mob riding a player, afterwards, if the player logged off, went through nether portal, etc, any mobs riding them would be deleted, this deleted pokemobs.

When vanilla added parrots, it added its own way to do mobs on shoulders, by making them not actually real, and just rendered there. I used this for the pokemobs.  The problem is, that vanilla kicks mobs off shoulders when the player jumps.

**Comment by CorentG** [comment]
Parrots were added in 1.12. So pokemobs not getting kicked off was a bug from pokecube's side ? Weird, it was so more convenient this way, vanilla parrots are annoying for this reason.
