### ISSUE TITLE
Legendary Error messages need improving

### ISSUE THREAD

**Issue by iilonmasc** [Pokecube-Development/Pokecube-Issues-and-Wiki#599]
#### What happens:
Trying to spawn Rayquaza in a generated Sky Pillar with the Ancient Stone item (which is listed as item needed for Rayquaza) results in the Message "Ho-Oh does not seem to spawn in this Location".

Tested in self-made Modpack and the Official Pokecube Modpack

#### What you expected to happen:
Using the Ancient Stone on the Legendary Spawner in a Sky Pillar spawns Rayquaza

#### Steps to reproduce:

1. Start a world in Creative
2. Get an Ancient Stone
3. Search a Sky Pillar and use (right click) the Stone on the Legendary Spawner.

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 3.6.0b and 3.7.1
- Minecraft: 1.16.4
- Forge: 35.1.9 and 35.1.28

**Comment by Thutmose** [comment]
It currently selects a random one of the error messages if you try to spawn a legend from a block, if that block supports multiple legends. I will see about improving the error message selection so it picks the "best" match, instead of a random one. In this case, it should give the "rayquaza doesn't trust you" error instead of "ho-oh not here", which is also correct
