### ISSUE TITLE
Unable to have Certain Pokemobs follow commands when chosing attack. (Investigating)

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Pokecube-Development/Pokecube-Issues-and-Wiki#6]
Any issues which report bugs, must fill out this form, otherwise they will be immediately closed with no response.
If your bug involves a crash, it *MUST* include a crash report. Failure to include the crash report without a good reason to not include it, will result in your issue being immediately closed.

#### Issue Description:
Unable to command Pokecubes with num leys 1234 during a battle

#### What happens:
Pokemobs enter a battle and whatever command attack they had at the time - is all they can do or the alternative they keep randomly choosing moves.

#### What you expected to happen:
I control my pokemobs and can command what attacks they get to use.

#### Steps to reproduce:

If my theory is correct the bug should be gone ... maybe its mob specific too.
reloaded game.
made a new world.
chose piplup
the bug returned.
spamming 2 to switch to growl.
worked after battle ended.
Did arrow trick by hovering until bar turned green then arrowed to first move - now I can select moves during a fight.
grabbed a different starter
still able to select moves during battle

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in, if using AIO, list that instead.

pokecube-aio-1.12.2-1.6.15.jar - pokecube-aio-1.12.2-1.6.20.jar
- Minecraft: 1.12.2
- Forge: 14.23.4.2755 - Forge: 14.23.4.2760

**Comment by P3rf3ctXZer0** [comment]
![2018-09-22 19_07_35-thutmose erlos gamergirl9219 - discord](https://user-images.githubusercontent.com/10351221/45922783-22ed8580-be9b-11e8-9ed9-7cd861d5ee53.jpg)
![2018-09-22 19_07_44-thutmose erlos gamergirl9219 - discord](https://user-images.githubusercontent.com/10351221/45922784-22ed8580-be9b-11e8-8a8b-7551dfb6a8a7.jpg)
![2018-09-22 19_07_53-thutmose erlos gamergirl9219 - discord](https://user-images.githubusercontent.com/10351221/45922785-22ed8580-be9b-11e8-9af2-a92e56cc5198.jpg)
![2018-09-22 19_08_02-thutmose erlos gamergirl9219 - discord](https://user-images.githubusercontent.com/10351221/45922786-22ed8580-be9b-11e8-9bd5-a75a404eda06.jpg)
![2018-09-22 19_08_10-thutmose erlos gamergirl9219 - discord](https://user-images.githubusercontent.com/10351221/45922787-23861c00-be9b-11e8-89e1-8f703f449e8d.jpg)
![2018-09-22 19_08_18-thutmose erlos gamergirl9219 - discord](https://user-images.githubusercontent.com/10351221/45922788-23861c00-be9b-11e8-8bc4-c82119b3641a.jpg)
![2018-09-22 19_08_32-thutmose erlos gamergirl9219 - discord](https://user-images.githubusercontent.com/10351221/45922789-23861c00-be9b-11e8-8f6c-97387b154cb1.jpg)
![2018-09-22 19_08_47-thutmose erlos gamergirl9219 - discord](https://user-images.githubusercontent.com/10351221/45922790-23861c00-be9b-11e8-9a6b-be36ea1d3195.jpg)
![2018-09-22 19_08_57-thutmose erlos gamergirl9219 - discord](https://user-images.githubusercontent.com/10351221/45922791-23861c00-be9b-11e8-9069-6e15df923400.jpg)
![2018-09-22 19_09_17-thutmose erlos gamergirl9219 - discord](https://user-images.githubusercontent.com/10351221/45922792-23861c00-be9b-11e8-9b1d-cf18df75d592.jpg)
![2018-09-22 19_09_28-thutmose erlos gamergirl9219 - discord](https://user-images.githubusercontent.com/10351221/45922793-23861c00-be9b-11e8-8753-3493e00cb919.jpg)
![2018-09-22 19_09_37-thutmose erlos gamergirl9219 - discord](https://user-images.githubusercontent.com/10351221/45922794-23861c00-be9b-11e8-822f-713e546cf768.jpg)

**Comment by P3rf3ctXZer0** [comment]
Issue does not exist in verison https://minecraft.curseforge.com/projects/pokecube-aoi/files/2593471

**Comment by Thutmose** [comment]
From that, seems like it might be related to one of the commits near this one:

https://github.com/Thutmose/Pokecube/commit/25e45720b01232dbb60c3d8a8355a3ea58947dd6

**Comment by P3rf3ctXZer0** [comment]
I can confirm that bug I mentioned from Pokecube alternative is indeed affected by this bug.

**Comment by P3rf3ctXZer0** [comment]
pokecube-aio-1.12.2-1.6.23.jar Fixed.

**Comment by Travis9x** [comment]
This bug is back.  It seems completely random, whether I am able to order a specific move to be used, or the pokemob just randomly chooses whatever it wants to use.  When the pokemob is deciding what to use, I cannot change the move selection.  For example, I press the down arrow key, and the move selection will very briefly change one slot down, but immediately go back up to what the pokemob wants to use.  This only happens during battle.  Outside of battle, I can change the move selection and it will stick, but as soon as another battle starts the pokemob will start deciding moves on its own again (regardless of whether I specifically tell the pokemob to attack something, or that something attacks me).  
I have triple-checked to make sure auto move selection is NOT turned on / enabled.

**Comment by Thutmose** [comment]
Is your pokemob set to guard?

**Comment by Travis9x** [comment]
>           Is your pokemob set to guard?

No, sorry, I forgot to mention that I checked that as well.

**Comment by Travis9x** [comment]
Update:  strangely, I have not been able to recreate this bug for a few days.  Or at the very least, it may have only been affecting the Pokémob that I was primarily using at the time.  I have not observed the bug with the other Pokémobs I've been using since then.

**Comment by P3rf3ctXZer0** [comment]
@Travis9x was it a water type?

**Comment by P3rf3ctXZer0** [comment]
Yeah - you are having the same issue. Try with other water types and see if the issue still exists!

**Comment by Travis9x** [comment]
Well, it seems Carvanha, Frillish, and Gyarados are all OK.  I haven't experienced the bug with any of them.

**Comment by BalHum** [comment]
Yeah, Mareanie, Koffing, Gyarados, Dratini and Dugtrio are behaving like this, it's not always.
I'm using pokecube-aio-1.8.0, mc-1.12.2 and forge 14.23.5.2768.

**Comment by P3rf3ctXZer0** [comment]
To my knowledge all water Pokemon can be susceptible to the bug by some always have this issue like Mareanie is a great example.

**Comment by Travis9x** [comment]
I agree with BalHum.  I believe all Pokémobs can potentially be affected by this bug, but water types are especially vulnerable for whatever strange reason.

**Comment by P3rf3ctXZer0** [comment]
Any updates on this issue @Thutmose?

**Comment by AlluringEmerald** [comment]
Okay, so after testing things, I started to discover a pattern of what pokemon were victim to this bug, what connected them. They usually had a move that they would default to, for instance in my case it was water gun, which might explain why water types are very prone to the bug. I tested out water gun on other pokemon, that wouldn't normally be able to learn water gun, and the bug affected most of them, but not all of them, defaulting to water gun whenever they went into combat. This included charmander, funny enough. There might be certain moves that are triggering the bug, because once I got a water type that didn't have water gun, or replaced the move, the bug was gone. So from my findings I seems water gun causes the bug on some level.

**Comment by Thutmose** [comment]
this bug wasn't fixed in the bug fix pass this weekend, due to the issue being closed, please do not close the issue if it is still occurring...

**Comment by P3rf3ctXZer0** [comment]
I just assumed you didn't plan on fixing it. I figured I would give up just stick with pixelmon since the bug makes the experience unplayable. Otherwise if this bug was not present the game would be incredible but it has been in the mod in some form since 1.10.2 and quite honestly if feel the only way you will be able to fix it is a full re-write.

**Comment by Thutmose** [comment]
Na, this bug is considered "minor and low priority" as it doesn't affect core balance to much, and is similar enough to existing mechanics.

My case for "minor and low priority": The large number of players who have not complained that this bug makes the game unplayable, and have not even noticed it.

It does not require a full re-write to fix, as the bug is somewhere in 3 AI classes, it is just a matter of figuring out which one it is in.

Any turn-based or otherwise combat adjustment addons wouldn't even have this bug, as they would be outright suppressing those 3 classes to implement their own combat system

**Comment by P3rf3ctXZer0** [comment]
Is there even a turn based mod?

**Comment by Thutmose** [comment]
there is a prototype of one in pokecube server utilities, as far as I can tell, noone really wants one, as noone has offered to help improve/update it.

**Comment by P3rf3ctXZer0** [comment]
Could be a case like me where maybe they just lack the skill to add or remove anything. A lot of the skilled coders do not make mods directly in the service of others. You were one of 3 people in 5 years to ever code anything for me directly.

**Comment by Thutmose** [comment]
I found some cases where the pokemobs were a bit too agressive on their hunting AI, which results in something very much like this bug. I reduced the effect, hopefully it fixes it sufficiently.
