### ISSUE TITLE
Worldgen configuration options?

### ISSUE THREAD

**Issue by hairlessOrphan** [Pokecube-Development/Pokecube-Issues-and-Wiki#622]
**Is your feature request related to a problem? Please describe.**
- Villages are generating everywhere, which causes significant server lag.
- Villages also don't seem to generate any of the newer structures in vanilla, especially the various professions buildings.
- Gyms, temples, and headquarters are generating everywhere, which reduce open real estate for builders.
- Professor only seems to generate in the first Pokemart, and then disappears after a few days. So if you don't get your starter Pokemob immediately, you might not be able to get one at all.

**Describe the solution you'd like**
- Configuration options to adjust or turn off various Pokecube worldgen features.
- Descriptions about which worldgen features are required for Pokecube progression (for example, it seems like the evolution items are only available from Pokemart traders, so we'd want options to reduce Pokemart frequency, plus some indication that if we disable Pokemarts entirely we'd lose the ability to evolve certain Pokemobs).

**Describe alternatives you've considered**
Tackling each of these issues one at a time could also be an option; issues with the Professor is the most obvious thing that could be tackled separately. For example, allowing the Professor to persist would help. Being able to summon a Professor (maybe as a profession block) would also help.

**Comment by Thutmose** [comment]
you can configure all of the worldgen via datapacks, they allow adding, removing, or otherwise adjusting all of the structures in the worldgen.

the next update will include a bunch of the additional vanilla structures as well.
It will also make the default structures rarer.

The professor should stay in the general area of the first one, and shouldn't disappear unless killed, It is generally recommended to use nbt editing to make him invulnerable if you are on a server, on single player it isn't so important. You can also set configs to enable the gui choice when logging in, instead of needing professor.

The items sold by traders can also be sold by random trainers, though at a lower rate, so most of those items are obtainable via the random trainers which can spawn outside of villages, this includes the evolution items, though maybe not some of the legendary items. These trade lists can also be adjusted via datapacks, so you can add whatever trades you want to the random trainers as well.

**Comment by hairlessOrphan** [comment]
Cool! Is there any documentation on how to adjust village frequency via datapack?

I'm pretty sure the Professor wasn't killed; we boxed up the pokemart on spawn because that was our first guess, too. But even with the entire Pokemart walled off, he disappeared after a few days (without the chunk loaded; we spread pretty far out). So that might be something to look at!

We disabled the `guiOnLogin` option because we found that (due to worldgen often placing villages on very uneven terrain) we would often spawn in either suffocating in rock or sinking / drowning in water, which didn't give us a lot of time to think about our starter pokemob. Hence going with the Professor option.

**Comment by Thutmose** [comment]
you could press escape, get out of the gui, then relog somewhere safer to have the choice

I will look into the despawning, they shouldn't do that, though they are liable to get killed by say zombie sieges, etc

**Comment by Thutmose** [comment]
I have not made a page for the worldgen datapacks yet, when I do, it will be here: https://pokecube.readthedocs.io/en/latest/datapacks/index.html

generally you include this: https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/blob/1.16/src/main/resources/data/pokecube/structures/worldgen.json and this: https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/blob/1.16/src/main/resources/data/pokecube_legends/structures/worldgen.json in a datapack, and put it in /config/pokecube/datapacks/, and then it will replace the ones in the jar, you can adjust rarity via the distance and separation values for the structures, such as here: https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/blob/1.16/src/main/resources/data/pokecube_legends/structures/worldgen.json#L440-L441

**Comment by Thutmose** [comment]
I updated the readthedocs to include a section on worldgen stuff:

https://pokecube.readthedocs.io/en/latest/datapacks/editing_worldgen.html
