### ISSUE TITLE
Server Crash related to Pokecube NPC

### ISSUE THREAD

**Issue by Awec4** [Pokecube-Development/Pokecube-Issues-and-Wiki#769]
#### Issue Description:
Server crashes repeatedly near a village. I don't know if it helps but I had non-Pokemob animals and hostiles turned on and re-enabled vanilla villages to spawn.

#### What happens:
Server crashes repeatedly near a village.

#### What you expected to happen:
The server to not crash

#### Steps to reproduce:

1. Wander around for a while
2. See a village nearby on the minimap
3. Server crashes
4. Restart the server and log back in
5. Server crashes

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO:
- Minecraft: 1.16.5
- Forge: 36.2.2
- Too many other mods to list but they're all in the crash report
[crash-reports_crash-2021-08-20_16.04.24-server.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/7022843/crash-reports_crash-2021-08-20_16.04.24-server.txt)

**Comment by Awec4** [comment]
Might be fixed by https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/commit/817123430a5be6f3672e97786a18434bd85ea2cb#diff-743aa91ef11c30ff6fba3f21661ec765bc4bda99e1b048bf6c9c7aea2030fc90 so if you could make a release with that it'd be appreciated

**Comment by Thutmose** [comment]
Yep, that is the fix for it, I will upload a server-side patch with the fix, it is only needed server side, the patched version will be "3.12.1", but will still work with 3.12.0.

It is the server jar here: https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/releases/tag/1.16.5-3.12.0

I will leave this issue open, so others can see the note for this link.
