### ISSUE TITLE
Rename the "Notch" trainer

### ISSUE THREAD

**Issue by xigzagoon** [Pokecube-Development/Pokecube-Issues-and-Wiki#866]
The guy is such a shitstain on humanity that Mojang scrubbed his name off of anything related to Minecraft and there's a big meme about how actually Hatsune Miku made Minecraft. Everyone hates the dude and for good reason. I don't want to be reminded he exists.

**Comment by Thutmose** [comment]
Just because he was a horrible person does not undo the fact that he was the creator of Minecraft...

You can remove that npc via a datapack or rename it via a resourcepack.

Removal involves editing this file: <https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/blob/1.18/src/main/resources/data/pokecube_mobs/database/trainer/trainers.json#L387-L399>

Renaming involves editing this file:
https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/blob/1.18/src/main/resources/assets/pokecube_adventures/lang/en_us.json#L94

This will not be done in the main mod.
