### ISSUE TITLE
Daycare block "fuel"

### ISSUE THREAD

**Issue by DigiGlitch** [Pokecube-Development/Pokecube-Issues-and-Wiki#93]
#### Issue Description:
Daycare block and use berries as its fuel source rather than emeralds

#### What happens:
when you place berries in the emerald slot, it will use it the same as an emerald. this actually also causes another issue allowing people to turn berries to emeralds by crafting an emerald with the produced emerald shards.

#### What you expected to happen:
for the daycare block not to allow the use of the item either by not allowing the player to put it in the slot or check if an emerald is being used.

#### Steps to reproduce:

1. place down a daycare block
2. place one or more berries into the emerald slot.
3. place a pokemob nearby to start gaining levels
____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core: 1.15.11
- Minecraft: 1.12.2
- Forge: 14.23.5.2768

**Comment by DeathExDorumon** [comment]
I may have stumbled upon the cause of this. I was making a trade with a custom npc trader and noticed he took my berries instead of feathers. After experimenting they seem like they just kinda ore dictionary with the most random things, like soul sand, feathers, and even dragons breath, although it wouldn't work for most crafting recipes unless they call for the proper ore dictionary term I believe. It shows up with the Custom NPC trader because it matches all ore dictionary terms

**Comment by Thutmose** [comment]
ahh, ya, I wonder if it is matching the "held item" ore dictionary tag...
